sudo: false
language: node_js
node_js:
- 'node'
deploy:
  - provider: npm
    email: waltshirey@gmail.com
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "js-library-travis-ci"
    upload_dir: lib/$TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api-key: $GITHUB_AUTH_TOKEN
    file: lib/index.js
    skip_cleanup: true
    on:
      tags: true
